// @require      file:///D:\DataFile\other\idea\project\BiBiBSPUserVideoMonkeyScript\util\Util.js
// @require      file:///D:\DataFile\other\idea\project\BiBiBSPUserVideoMonkeyScript\util\HttpUtil.js
// @require      file:///D:\DataFile\other\idea\project\BiBiBSPUserVideoMonkeyScript\Layout.js
// @require      file:///D:\DataFile\other\idea\project\BiBiBSPUserVideoMonkeyScript\LocalData.js
// @require      file:///D:\DataFile\other\idea\project\BiBiBSPUserVideoMonkeyScript\Perf_observer.js
// @require      file:///D:\DataFile\other\idea\project\BiBiBSPUserVideoMonkeyScript\AccountCenter.js
// @require      file:///D:\DataFile\other\idea\project\BiBiBSPUserVideoMonkeyScript\FrequencyChannel.js
// @require      file:///D:\DataFile\other\idea\project\BiBiBSPUserVideoMonkeyScript\Live.js
// @require      file:///D:\DataFile\other\idea\project\BiBiBSPUserVideoMonkeyScript\Bilibili.js
// @require      file:///D:\DataFile\other\idea\project\BiBiBSPUserVideoMonkeyScript\BilibiliOne.js
// @require      file:///D:\DataFile\other\idea\project\BiBiBSPUserVideoMonkeyScript\RuleList.js
// @require      file:///D:\DataFile\other\idea\project\BiBiBSPUserVideoMonkeyScript\other\Github.js
// @require      file:///D:\DataFile\other\idea\project\BiBiBSPUserVideoMonkeyScript\BIBIShield.js